import test from'node:test';
import assert from'node:assert/strict';
import{mergeProgressData,mergeSnapshots}from'../src/progress_merge.js';
import{completeJapaneseLesson,defaultJapaneseProgress}from'../src/japanese_course_logic.js';
import{aggregateXpEvents,isStoryLessonBoundary,lessonEventKey,storyXpIdentity,xpForLanguage,xpForLesson}from'../src/xp_service.js';

test('combina desbloqueos y lecciones sin duplicarlos',()=>{const result=mergeProgressData({completedLessons:['a'],unlockedUnits:['u1']},{completedLessons:['a','b'],unlockedUnits:['u2']});assert.deepEqual(result.completedLessons,['a','b']);assert.deepEqual(result.unlockedUnits,['u1','u2']);});
test('no suma XP ni reduce la mejor puntuación',()=>{const result=mergeProgressData({xp:120,lessonScores:{a:{percentage:90}}},{xp:100,lessonScores:{a:{percentage:70},b:{percentage:80}}});assert.equal(result.xp,120);assert.equal(result.lessonScores.a.percentage,90);assert.equal(result.lessonScores.b.percentage,80);});
test('fusiona dominio por elemento y conserva el estado más fuerte',()=>{const result=mergeProgressData({masteryByItem:{x:{correct:3,wrong:1,stage:2,lastSeen:'2026-01-01'}}},{masteryByItem:{x:{correct:2,wrong:4,stage:1,lastSeen:'2026-02-01'}}});assert.deepEqual(result.masteryByItem.x,{correct:3,wrong:4,stage:2,lastSeen:'2026-02-01'});});
test('fusiona documentos por entityKey',()=>{const records=mergeSnapshots([{entityKey:'course:japanese',value:{xp:10,completedLessons:['a']}}],[{entityKey:'course:japanese',value:{xp:20,completedLessons:['b']}}]);assert.equal(records.length,1);assert.equal(records[0].value.xp,20);assert.deepEqual(records[0].value.completedLessons,['a','b']);});
test('el progreso japonés completa una lección sin mantener un contador XP paralelo',()=>{const lesson={id:'l1',activities:[]},unit={id:'u1',lessons:[lesson]},result={percentage:100,correct:1,total:1,xp:10,errors:[]};const first=completeJapaneseLesson(defaultJapaneseProgress(),unit,lesson,result,new Date('2026-01-01T12:00:00Z')),second=completeJapaneseLesson(first,unit,lesson,result,new Date('2026-01-02T12:00:00Z'));assert.equal(first.xp,0);assert.equal(second.xp,0);assert.deepEqual(second.completedLessons,['l1']);});
test('las reglas de XP son centrales y respetan una recompensa explícita',()=>{assert.equal(xpForLesson({lessonType:'normal'}),20);assert.equal(xpForLesson({lessonType:'review'}),5);assert.equal(xpForLesson({lessonType:'test'}),30);assert.equal(xpForLesson({xpReward:42}),42);});
test('combina XP japonés y coreano por idioma',()=>{const result=aggregateXpEvents([{languageId:'Japanese',xp:20,status:'confirmed',earnedAt:'2026-01-01'},{languageId:'Korean',xp:30,status:'confirmed',earnedAt:'2026-01-02'}]);assert.equal(result.totalXp,50);assert.equal(result.byLanguage.japanese,20);assert.equal(result.byLanguage.korean,30);});
test('el mapa de un idioma extrae solo su XP y normaliza alias',()=>{const summary={totalXp:412,byLanguage:{Japanese:132,ja:8,english:272}};assert.equal(xpForLanguage(summary,'japanese'),140);assert.equal(xpForLanguage(summary,'english'),272);});
test('cuenta finalizaciones reales sin confundir el ajuste histórico de XP',()=>{const result=aggregateXpEvents([{serverEventKey:'lesson-completed:japanese:course:l1',languageId:'Japanese',xp:0,status:'local',earnedAt:'2026-01-01'},{serverEventKey:'migration:japanese-legacy-v1',languageId:'Japanese',xp:100,status:'local',earnedAt:'2026-01-01'}]);assert.equal(result.completedLessons,1);assert.equal(result.totalXp,100);});
test('la clave de evento es determinista e independiente de la recarga',()=>{const input={languageId:'Japanese',courseId:'japanese-from-zero',lessonId:'jp-hira-01-family-1'};assert.equal(lessonEventKey(input),lessonEventKey({...input}));assert.equal(lessonEventKey(input),'lesson-completed:japanese:japanese-from-zero:jp-hira-01-family-1');});
test('las historias tienen identidad estable por libro y lección',()=>{assert.deepEqual(storyXpIdentity({bookCode:'HF-A1',lesson:12}),{courseId:'story:HF-A1',lessonId:'lesson:12'});assert.deepEqual(storyXpIdentity({bookCode:'CONTINUO',lesson:0}),{courseId:'story:CONTINUO',lessonId:'lesson:continuous'});});
test('solo el último audio de una lección completa la historia',()=>{const tracks=[{lesson:1},{lesson:1},{lesson:2}];assert.equal(isStoryLessonBoundary(tracks,0),false);assert.equal(isStoryLessonBoundary(tracks,1),true);assert.equal(isStoryLessonBoundary(tracks,2),true);});
