#!/usr/bin/env node
import fs from'node:fs';
import path from'node:path';
import{fileURLToPath}from'node:url';
import{BEGINNER_COURSES}from'../src/beginner_courses.js';
import{ZERO_COURSES}from'../src/data/zero_courses.js';
import{GUIDED_COURSES}from'../src/guided_course_config.js';

const here=path.dirname(fileURLToPath(import.meta.url)),web=path.resolve(here,'..'),library=JSON.parse(fs.readFileSync(path.join(web,'library/library.json'),'utf8'));
const unitPlan=[
  ['reading','Sonidos y lectura','Pronunciación y reglas básicas de lectura.','Aa'],
  ['survival','Comunicación esencial','Saludos, cortesía y expresiones para desenvolverte.','☀'],
  ['essentials','Pronombres y verbos esenciales','Ser, estar, tener, ir, querer, poder y hacer.','人'],
  ['questions','Preguntas y estructura','Orden, negación, preguntas y palabras interrogativas.','?'],
  ['time','Números, tiempo y vida diaria','Números, días, horas y expresiones cotidianas.','12'],
  ['vocabulary','Vocabulario frecuente','Palabras frecuentes organizadas en sesiones breves.','言'],
  ['reading-bridge','Escucha y lectura guiada','Oraciones graduadas con comprensión y audio.','文'],
  ['story-bridge','Puente hacia las historias','Consolida lo esencial antes de abrir tu primera historia.','本'],
];

const essentials={
English:`I|yo\nyou|tú / usted\nhe|él\nshe|ella\nwe|nosotros\nthey|ellos\nto be|ser / estar\nto have|tener\nto go|ir\nto want|querer\ncan|poder\nto do|hacer\nwhat|qué\nwho|quién\nwhere|dónde\nwhen|cuándo\nhow|cómo\nwhy|por qué\nnot|no / negación\nthis|esto / este\nthat|eso / ese\nhere|aquí\nthere|allí\nnow|ahora\ntoday|hoy\ntomorrow|mañana\nyesterday|ayer`,
Korean:`저|yo (formal)\n나|yo (informal)\n당신|usted / tú\n그|él\n그녀|ella\n우리|nosotros / nuestro\n그들|ellos\n이다|ser\n있다|haber / tener / estar\n가다|ir\n오다|venir\n원하다|querer\n할 수 있다|poder\n하다|hacer\n뭐 / 무엇|qué\n누구|quién\n어디|dónde\n언제|cuándo\n어떻게|cómo\n왜|por qué\n안|no / negación\n이것|esto\n그것|eso\n저것|aquello\n여기|aquí\n거기|ahí\n지금|ahora\n오늘|hoy\n내일|mañana\n어제|ayer`,
Russian:`я|yo\nты|tú\nвы|usted / ustedes\nон|él\nона|ella\nмы|nosotros\nони|ellos\nбыть|ser / estar\nиметь|tener\nидти|ir a pie\nехать|ir en transporte\nхотеть|querer\nмочь|poder\nделать|hacer\nчто|qué\nкто|quién\nгде|dónde\nкогда|cuándo\nкак|cómo\nпочему|por qué\nне|no / negación\nэто|esto / eso\nздесь|aquí\nтам|allí\nсейчас|ahora\nсегодня|hoy\nзавтра|mañana\nвчера|ayer`,
Italian:`io|yo\ntu|tú\nLei|usted\nlui|él\nlei|ella\nnoi|nosotros\nvoi|vosotros / ustedes\nloro|ellos\nessere|ser / estar\navere|tener\nandare|ir\nvenire|venir\nvolere|querer\npotere|poder\nfare|hacer\nche cosa|qué\nchi|quién\ndove|dónde\nquando|cuándo\ncome|cómo\nperché|por qué\nnon|no / negación\nquesto|esto\nquello|aquello\nqui|aquí\nlì|allí\nadesso|ahora\noggi|hoy\ndomani|mañana\nieri|ayer`,
French:`je|yo\ntu|tú\nvous|usted / ustedes\nil|él\nelle|ella\nnous|nosotros\nils / elles|ellos / ellas\nêtre|ser / estar\navoir|tener\naller|ir\nvenir|venir\nvouloir|querer\npouvoir|poder\nfaire|hacer\nquoi / que|qué\nqui|quién\noù|dónde\nquand|cuándo\ncomment|cómo\npourquoi|por qué\nne… pas|no / negación\nceci|esto\ncela|eso\nici|aquí\nlà|allí\nmaintenant|ahora\naujourd’hui|hoy\ndemain|mañana\nhier|ayer`,
German:`ich|yo\ndu|tú\nSie|usted / ustedes\ner|él\nsie|ella / ellos\nwir|nosotros\nihr|vosotros\nsein|ser / estar\nhaben|tener\ngehen|ir\nkommen|venir\nwollen|querer\nkönnen|poder\nmachen|hacer\nwas|qué\nwer|quién\nwo|dónde\nwann|cuándo\nwie|cómo\nwarum|por qué\nnicht|no / negación\ndies|esto\ndas|eso\nhier|aquí\ndort|allí\njetzt|ahora\nheute|hoy\nmorgen|mañana\ngestern|ayer`,
Chinese:`我|yo\n你|tú\n您|usted\n他|él\n她|ella\n我们|nosotros\n他们|ellos\n是|ser\n有|tener / haber\n去|ir\n来|venir\n想|querer / pensar\n能 / 可以|poder\n做|hacer\n什么|qué\n谁|quién\n哪里|dónde\n什么时候|cuándo\n怎么|cómo\n为什么|por qué\n不|no / negación\n这|esto\n那|eso / aquello\n这里|aquí\n那里|allí\n现在|ahora\n今天|hoy\n明天|mañana\n昨天|ayer`,
Portuguese:`eu|yo\ntu / você|tú / usted\nele|él\nela|ella\nnós|nosotros\nvocês|ustedes\neles / elas|ellos / ellas\nser|ser\nestar|estar\nter|tener\nir|ir\nvir|venir\nquerer|querer\npoder|poder\nfazer|hacer\no que|qué\nquem|quién\nonde|dónde\nquando|cuándo\ncomo|cómo\npor que|por qué\nnão|no / negación\nisto|esto\nisso|eso\naqui|aquí\nali|allí\nagora|ahora\nhoje|hoy\namanhã|mañana\nontem|ayer`,
Arabic:`أنا|yo\nأنتَ / أنتِ|tú\nهو|él\nهي|ella\nنحن|nosotros\nأنتم|ustedes\nهم|ellos\nكان|ser / estar\nعندي|tener\nذهب|ir\nأتى|venir\nأريد|quiero\nأستطيع|puedo\nأفعل|hacer\nماذا / ما|qué\nمن|quién\nأين|dónde\nمتى|cuándo\nكيف|cómo\nلماذا|por qué\nلا|no / negación\nهذا|esto (masculino)\nهذه|esto (femenino)\nذلك|aquello\nهنا|aquí\nهناك|allí\nالآن|ahora\nاليوم|hoy\nغدًا|mañana\nأمس|ayer`,
};

const parseLines=text=>String(text||'').trim().split('\n').filter(Boolean).map(line=>{const[target,meaning]=line.split('|');return{target:target.trim(),meaning:meaning.trim(),hint:meaning.trim()};});
const clean=value=>String(value||'').replace(/\s+/g,' ').trim();
const hasHan=value=>/[\u3400-\u9fff]/u.test(String(value||''));
const unique=items=>{const seen=new Set;return items.filter(item=>{item.target=clean(item.target);item.meaning=clean(item.meaning);if(!item.target||!item.meaning){return false;}const key=item.target.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true;});};
const bookItems=language=>{const words=[],phrases=[];for(const entry of library.books.filter(book=>book.target_language===language)){const manifestPath=path.join(web,'library',entry.manifest);if(!fs.existsSync(manifestPath))continue;const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));for(const track of manifest.tracks||[]){const item={target:track.text,meaning:track.translation,hint:track.translation};if(track.type==='word')words.push(item);else if(track.type==='phrase')phrases.push(item);}const explanationPath=path.join(path.dirname(manifestPath),'explanations','track_explanations.json');if(fs.existsSync(explanationPath)){const data=JSON.parse(fs.readFileSync(explanationPath,'utf8'));for(const explanation of Object.values(data.items||{}))for(const part of explanation.breakdown||[])words.push({target:part.part,meaning:part.meaning_es,hint:part.meaning_es});}}
return{words:unique(words),phrases:unique(phrases)};};
const zeroItems=(language,stageIds=null)=>{const stages=ZERO_COURSES[language]?.stages||[],result=[];for(const stage of stages.filter(stage=>!stageIds||stageIds.includes(stage.id)))for(const item of stage.items||[]){if(item.details?.length)for(const detail of item.details)result.push({target:detail.text,meaning:detail.meaning,hint:item.explanation||detail.meaning});else result.push({target:item.speak||item.symbol,meaning:item.example||item.explanation||item.hint,hint:item.explanation||item.hint});}return unique(result);};
const beginnerItems=language=>unique((BEGINNER_COURSES[language]?.groups||[]).flatMap(group=>group.items.map(item=>({target:item.speak||item.symbol,display:item.symbol,meaning:item.hint||item.example,hint:`${item.symbol}: ${item.hint||item.example}`,group:group.title}))));
const seedItems=language=>{const seedPath=path.join(web,'library','courses',language,'vocabulary_seed.json');if(!fs.existsSync(seedPath))return[];const data=JSON.parse(fs.readFileSync(seedPath,'utf8'));return unique((data.items||[]).map(item=>({target:item.target,meaning:item.meaning,hint:item.example?`${item.meaning}. Ejemplo: ${item.example}${item.example_meaning?` — ${item.example_meaning}`:''}`:item.meaning,example:item.example||'',example_meaning:item.example_meaning||'',category:item.category||''})));};
const pickOptions=(pool,item,index)=>{const meanings=pool.map(value=>value.meaning).filter(Boolean),options=[item.meaning];for(let offset=1;options.length<3&&offset<meanings.length+2;offset++){const candidate=meanings[(index+offset*7)%meanings.length];if(candidate&&!options.includes(candidate))options.push(candidate);}return options.sort((a,b)=>((a.length+index)%5)-((b.length+index)%5));};
const pickWrittenOptions=(pool,item,index)=>{const written=pool.map(value=>value.display||value.target).filter(Boolean),correct=item.display||item.target,options=[correct];for(let offset=1;options.length<3&&offset<written.length+2;offset++){const candidate=written[(index+offset*7)%written.length];if(candidate&&!options.includes(candidate))options.push(candidate);}return options.sort((a,b)=>((String(a).length+index)%5)-((String(b).length+index)%5));};
const chineseCharacterFirst=items=>items.map(item=>{if(hasHan(item.meaning)&&!hasHan(item.target)){const pinyin=item.target,display=item.meaning,spanish=item.hint&&item.hint!==display?item.hint:'Consulta el significado y escucha la pronunciación.';return{...item,target:display,display,meaning:spanish,hint:spanish,audio:pinyin,pinyin};}return item;});
const activityBase=(id,type,prompt,target,options,answer,explanation,audio='',gradable=true)=>({id,type,prompt,target,options,answer,explanation,audio,slow_audio:audio,image:null,writing_asset:null,tags:[],xp:gradable?10:2,...(!gradable?{gradable:false}:{})});
function makeLesson(slug,unitId,index,title,items,pool,{review=false,test=false}={}){const id=`${slug}-${unitId}-${review?'review-':test?'test-':''}${String(index+1).padStart(2,'0')}`,reading=unitId==='reading',activities=[activityBase(`${id}-intro`,'lesson_intro',title,'',[],'',review?'Repasa una muestra de lo aprendido.':'Primero aprenderás cada elemento y después lo practicarás.','',false)];items.forEach((item,itemIndex)=>{const key=`${id}-${itemIndex+1}`,display=item.display||item.target,audio=item.audio||item.target,pinyinFields=item.pinyin?{pinyin:item.pinyin,pinyin_mode:unitId==='survival'&&index<2&&!review&&!test?'visible':'hidden'}:{};if(!review&&!test)activities.push({...activityBase(`${key}-teach`,'teach_concept',`Aprende y escucha`,display,[],'',item.hint||item.meaning,audio,false),sound_hint:item.hint||item.meaning,...pinyinFields});activities.push({...activityBase(`${key}-meaning`,'select_translation',reading?`¿Cómo se pronuncia «${display}»?`:`¿Qué significa «${display}»?`,display,pickOptions(pool,item,index+itemIndex),item.meaning,item.meaning,audio),...pinyinFields});activities.push(activityBase(`${key}-listen`,'listening_choice',reading?'Escucha y elige la letra o símbolo correcto':'Escucha y elige la palabra o frase correcta','',pickWrittenOptions(pool,item,index+itemIndex+3),display,reading?`El sonido corresponde a «${display}».`:`La forma escrita correcta es «${display}»: ${item.meaning}.`,audio));});return{id,title,description:review?'Repaso acumulativo breve.':test?'Prueba de dominio de la unidad.':`${items.length} ${items.length===1?'elemento nuevo':'elementos nuevos'} con práctica inmediata.`,...(review?{isReview:true}:{}),...(test?{isTest:true,isUnitFinal:true,xpReward:30}:{}),activities};}
function makeUnit(slug,plan,items){const[id,title,description]=plan,chunk=id==='vocabulary'?10:5,lessons=[];for(let start=0,startLesson=0;start<items.length;start+=chunk,startLesson++){const slice=items.slice(start,start+chunk);lessons.push(makeLesson(slug,id,startLesson,`${title} · ${startLesson+1}`,slice,items));if((startLesson+1)%3===0&&start+chunk<items.length){const learned=items.slice(0,start+chunk),sample=[...learned].slice(Math.max(0,learned.length-8)).filter((_,i)=>i%2===0).slice(0,4);lessons.push(makeLesson(slug,id,startLesson,`Repaso breve ${Math.floor((startLesson+1)/3)}`,sample,items,{review:true}));}}const testItems=items.filter((_,index)=>index%Math.max(1,Math.floor(items.length/10))===0).slice(0,10);if(testItems.length)lessons.push(makeLesson(slug,id,lessons.length,`Prueba · ${title}`,testItems,items,{test:true}));return{id,title,description,requirements:[],reward:{xp:Math.max(100,lessons.length*20),badge:title},lessons};}

for(const[language,definition]of Object.entries(GUIDED_COURSES)){
  if(language==='Japanese')continue;
  const books=bookItems(language),zero=zeroItems(language),survival=zeroItems(language,['survival','communication','repeat']),structure=zeroItems(language,['structure','dangerous','combinations']),communication=zeroItems(language,['communication']),time=communication.filter(item=>/número|hora|día|semana|tiempo|number|time|day/i.test(`${item.meaning} ${item.hint}`));
  const reading=beginnerItems(language),essential=unique([...parseLines(essentials[language]),...structure]),questions=unique([...parseLines(essentials[language]).filter(item=>/qué|quién|dónde|cuándo|cómo|por qué|negación/.test(item.meaning)),...communication.filter(item=>/[?？؟]/.test(item.target))]),daily=unique([...time,...survival]),vocabulary=unique([...seedItems(language),...books.words,...zero,...parseLines(essentials[language])]).slice(0,500),readingBridge=unique([...books.phrases,...survival]).slice(0,60),storyBridge=unique([...books.phrases.slice(60),...communication,...structure]).slice(0,30);
  if(language==='Chinese')for(const items of[zero,survival,daily,vocabulary,readingBridge,storyBridge])items.splice(0,items.length,...unique(chineseCharacterFirst(items)));
  const pools={reading,survival:unique([...survival,...zero]).slice(0,60),essentials:essential,questions,time:daily,vocabulary,'reading-bridge':readingBridge,'story-bridge':storyBridge};
  for(const key of Object.keys(pools))if(!pools[key].length)pools[key]=parseLines(essentials[language]).slice(0,10);
  const root=path.join(web,'library','courses',definition.directory),unitsRoot=path.join(root,'units');fs.mkdirSync(unitsRoot,{recursive:true});
  const summaries=[];unitPlan.forEach((plan,index)=>{const unit=makeUnit(definition.slug,plan,pools[plan[0]]);const filename=`${plan[0]}.json`;fs.writeFileSync(path.join(unitsRoot,filename),JSON.stringify(unit,null,2)+'\n');summaries.push({id:plan[0],world:index+1,title:plan[1],description:plan[2],manifest:`units/${filename}`,icon:definition.worldIcons?.[index]||plan[3]});});
  const coursePath=path.join(root,'course.json'),existingCourse=fs.existsSync(coursePath)?JSON.parse(fs.readFileSync(coursePath,'utf8')):null,generatedIds=new Set(unitPlan.map(plan=>plan[0])),additionalUnits=(existingCourse?.units||[]).filter(unit=>!generatedIds.has(unit.id));
  const course={courseId:`${definition.slug}-from-zero`,title:`${definition.name}: de cero a conversaciones intermedias`,language,languageCode:definition.languageCode,version:1,routeLabel:'RUTA GUIADA · DE CERO A B1',tagline:definition.tagline,vocabularyGoal:300,vocabularyPrepared:vocabulary.length,levels:[{id:'route-a1',title:'Preparación para historias A1'}],unlockRules:{minimumScore:85,masteryScore:95},recommendedBooks:library.books.filter(book=>book.target_language===language).map(book=>({code:book.code,title:book.title,requiredWorld:8,requiredScore:85})),...(existingCourse||{}),units:[...summaries,...additionalUnits]};
  fs.writeFileSync(coursePath,JSON.stringify(course,null,2)+'\n');
  const manifestPath=path.join(root,'audio_manifest.json');if(!fs.existsSync(manifestPath))fs.writeFileSync(manifestPath,JSON.stringify({schema_version:1,provider:'ElevenLabs',language,language_code:definition.languageCode,model_id:'eleven_v3',items:{}},null,2)+'\n');
  console.log(`${language}: ${summaries.length} mundos · ${summaries.reduce((sum,item)=>sum+JSON.parse(fs.readFileSync(path.join(root,item.manifest))).lessons.length,0)} pasos · ${vocabulary.length}/300 palabras preparadas`);
}
