// A2.1 conecta pasado, futuro, comparación, modalidad y resolución de
// problemas. Cada idioma usa formas naturales propias; CJK no usa
// transcripción latina como objetivo visible.

export const A21_THEMES=Object.freeze([
  {id:'past',title:'Lo que pasó',objective:'Narrar actividades y experiencias pasadas en orden.',meanings:['ayer','anoche','la semana pasada','primero','después','finalmente','ocurrió','terminó','Ayer trabajé hasta tarde.','Llegué a casa a las nueve.','Primero llamé a mi amigo.','Después fuimos a cenar.','No pude encontrar mis llaves.','¿Qué pasó?','Fue una experiencia interesante.','Al final todo salió bien.']},
  {id:'future',title:'Planes y futuro',objective:'Expresar intención, predicción y planes acordados.',meanings:['plan','intención','promesa','quizá','seguro','próximo','reservar','decidir','Voy a estudiar esta noche.','Mañana visitaré a mi familia.','Quizá llueva el sábado.','Ya hemos decidido la fecha.','Pienso reservar una habitación.','Te llamaré cuando llegue.','¿Qué vas a hacer después?','El próximo año quiero viajar.']},
  {id:'comparison',title:'Describir y comparar',objective:'Comparar personas, lugares, objetos y opciones.',meanings:['más','menos','igual','diferente','mejor','peor','alto','rápido','Este tren es más rápido.','La habitación es menos cara.','Los dos tienen el mismo tamaño.','Mi ciudad es diferente de esta.','Esta opción es mejor para mí.','Hoy hace peor tiempo que ayer.','¿Cuál es el edificio más alto?','Prefiero el camino más corto.']},
  {id:'ability',title:'Capacidad y obligación',objective:'Expresar capacidad, permiso, necesidad y prohibición.',meanings:['poder','saber','necesitar','deber','permitido','prohibido','necesario','posible','Puedo hacerlo solo.','Sé cocinar un poco.','Tengo que salir temprano.','Debes mostrar tu pasaporte.','Aquí se puede tomar fotos.','No se puede fumar aquí.','¿Puedo usar este asiento?','No pude terminar a tiempo.']},
  {id:'services',title:'Servicios y problemas',objective:'Explicar un problema y negociar una solución.',meanings:['reserva','recibo','factura','reparación','devolución','error','roto','solución','Tengo una reserva a mi nombre.','La factura no es correcta.','Este aparato no funciona.','Quisiera cambiar este producto.','¿Me puede dar un recibo?','Necesito que lo reparen hoy.','¿Cuándo estará listo?','Gracias por resolver el problema.']},
  {id:'conversation',title:'Conversaciones conectadas',objective:'Mantener intercambios de varias intervenciones.',meanings:['de verdad','claro','quizá','entonces','además','sin embargo','por eso','entiendo','¿De verdad? Cuéntame más.','Claro, no hay problema.','Quizá podamos ir mañana.','Entonces nos vemos a las seis.','Además, necesito comprar comida.','Sin embargo, hoy no tengo tiempo.','Por eso llegué tarde.','Entiendo. ¿Y qué hiciste después?']},
]);

export const A21_TARGETS=Object.freeze({
  English:{icons:['Past','Next','↔','Can','Fix','Talk'],
    past:['yesterday','last night','last week','first','afterwards','finally','happened','ended','I worked late yesterday.','I got home at nine.','First, I called my friend.','Afterwards, we went out for dinner.','I could not find my keys.','What happened?','It was an interesting experience.','In the end, everything went well.'],
    future:['plan','intention','promise','perhaps','certain','next','to book','to decide','I am going to study tonight.','I will visit my family tomorrow.','It might rain on Saturday.','We have already decided on the date.','I plan to book a room.','I will call you when I arrive.','What are you going to do next?','I want to travel next year.'],
    comparison:['more','less','same','different','better','worse','tall','fast','This train is faster.','The room is less expensive.','They are both the same size.','My city is different from this one.','This option is better for me.','The weather is worse today than yesterday.','Which is the tallest building?','I prefer the shorter route.'],
    ability:['can','know how to','need to','must','allowed','forbidden','necessary','possible','I can do it by myself.','I know how to cook a little.','I have to leave early.','You must show your passport.','You can take photos here.','You must not smoke here.','May I use this seat?','I could not finish on time.'],
    services:['reservation','receipt','bill','repair','return','mistake','broken','solution','I have a reservation in my name.','The bill is not correct.','This device does not work.','I would like to exchange this product.','Could you give me a receipt?','I need it repaired today.','When will it be ready?','Thank you for solving the problem.'],
    conversation:['really','of course','maybe','then','besides','however','that is why','I understand','Really? Tell me more.','Of course, no problem.','Maybe we can go tomorrow.','Then I will see you at six.','Besides, I need to buy food.','However, I do not have time today.','That is why I was late.','I understand. What did you do next?']},
  French:{icons:['Hier','Après','↔','Pouvoir','Aide','Parler'],
    past:['hier','hier soir','la semaine dernière','d’abord','ensuite','finalement','est arrivé','s’est terminé','Hier, j’ai travaillé tard.','Je suis rentré à neuf heures.','D’abord, j’ai appelé mon ami.','Ensuite, nous sommes allés dîner.','Je n’ai pas pu trouver mes clés.','Qu’est-ce qui s’est passé ?','C’était une expérience intéressante.','À la fin, tout s’est bien passé.'],
    future:['projet','intention','promesse','peut-être','certain','prochain','réserver','décider','Je vais étudier ce soir.','Demain, je rendrai visite à ma famille.','Il pleuvra peut-être samedi.','Nous avons déjà décidé de la date.','Je compte réserver une chambre.','Je t’appellerai quand j’arriverai.','Qu’est-ce que tu vas faire ensuite ?','L’année prochaine, je veux voyager.'],
    comparison:['plus','moins','pareil','différent','meilleur','pire','haut','rapide','Ce train est plus rapide.','La chambre est moins chère.','Les deux ont la même taille.','Ma ville est différente de celle-ci.','Cette option est meilleure pour moi.','Il fait moins beau aujourd’hui qu’hier.','Quel est le bâtiment le plus haut ?','Je préfère le chemin le plus court.'],
    ability:['pouvoir','savoir','avoir besoin de','devoir','permis','interdit','nécessaire','possible','Je peux le faire tout seul.','Je sais un peu cuisiner.','Je dois partir tôt.','Vous devez montrer votre passeport.','On peut prendre des photos ici.','Il est interdit de fumer ici.','Je peux utiliser ce siège ?','Je n’ai pas pu finir à temps.'],
    services:['réservation','reçu','facture','réparation','retour','erreur','cassé','solution','J’ai une réservation à mon nom.','La facture n’est pas correcte.','Cet appareil ne fonctionne pas.','Je voudrais échanger ce produit.','Vous pouvez me donner un reçu ?','J’ai besoin qu’on le répare aujourd’hui.','Quand est-ce que ce sera prêt ?','Merci d’avoir résolu le problème.'],
    conversation:['vraiment','bien sûr','peut-être','alors','en plus','cependant','c’est pourquoi','je comprends','Vraiment ? Raconte-moi la suite.','Bien sûr, aucun problème.','On pourra peut-être y aller demain.','Alors, on se voit à six heures.','En plus, je dois acheter à manger.','Cependant, je n’ai pas le temps aujourd’hui.','C’est pourquoi je suis arrivé en retard.','Je comprends. Et qu’est-ce que tu as fait ensuite ?']},
  German:{icons:['Gestern','Morgen','↔','Können','Service','Dialog'],
    past:['gestern','gestern Abend','letzte Woche','zuerst','danach','schließlich','ist passiert','ist zu Ende gegangen','Gestern habe ich lange gearbeitet.','Ich bin um neun Uhr nach Hause gekommen.','Zuerst habe ich meinen Freund angerufen.','Danach sind wir essen gegangen.','Ich konnte meine Schlüssel nicht finden.','Was ist passiert?','Es war eine interessante Erfahrung.','Am Ende ist alles gut gegangen.'],
    future:['Plan','Absicht','Versprechen','vielleicht','sicher','nächste','reservieren','entscheiden','Ich werde heute Abend lernen.','Morgen besuche ich meine Familie.','Am Samstag regnet es vielleicht.','Wir haben das Datum schon beschlossen.','Ich möchte ein Zimmer reservieren.','Ich rufe dich an, wenn ich ankomme.','Was machst du danach?','Nächstes Jahr möchte ich reisen.'],
    comparison:['mehr','weniger','gleich','anders','besser','schlechter','hoch','schnell','Dieser Zug ist schneller.','Das Zimmer ist weniger teuer.','Beide sind gleich groß.','Meine Stadt ist anders als diese.','Diese Möglichkeit ist besser für mich.','Heute ist das Wetter schlechter als gestern.','Welches ist das höchste Gebäude?','Ich nehme lieber den kürzeren Weg.'],
    ability:['können','wissen, wie','brauchen','müssen','erlaubt','verboten','notwendig','möglich','Ich kann es allein machen.','Ich kann ein bisschen kochen.','Ich muss früh los.','Sie müssen Ihren Pass zeigen.','Hier darf man fotografieren.','Hier darf man nicht rauchen.','Darf ich diesen Platz benutzen?','Ich konnte nicht rechtzeitig fertig werden.'],
    services:['Reservierung','Quittung','Rechnung','Reparatur','Rückgabe','Fehler','kaputt','Lösung','Ich habe eine Reservierung auf meinen Namen.','Die Rechnung stimmt nicht.','Dieses Gerät funktioniert nicht.','Ich möchte dieses Produkt umtauschen.','Können Sie mir eine Quittung geben?','Ich brauche die Reparatur noch heute.','Wann wird es fertig sein?','Danke, dass Sie das Problem gelöst haben.'],
    conversation:['wirklich','natürlich','vielleicht','dann','außerdem','allerdings','deshalb','ich verstehe','Wirklich? Erzähl mir mehr.','Natürlich, kein Problem.','Vielleicht können wir morgen gehen.','Dann sehen wir uns um sechs.','Außerdem muss ich Essen kaufen.','Allerdings habe ich heute keine Zeit.','Deshalb bin ich zu spät gekommen.','Ich verstehe. Und was hast du danach gemacht?']},
  Italian:{icons:['Ieri','Domani','↔','Potere','Aiuto','Parlare'],
    past:['ieri','ieri sera','la settimana scorsa','prima','dopo','alla fine','è successo','è finito','Ieri ho lavorato fino a tardi.','Sono arrivato a casa alle nove.','Prima ho chiamato il mio amico.','Dopo siamo andati a cena.','Non sono riuscito a trovare le chiavi.','Che cosa è successo?','È stata un’esperienza interessante.','Alla fine è andato tutto bene.'],
    future:['piano','intenzione','promessa','forse','sicuro','prossimo','prenotare','decidere','Studierò stasera.','Domani andrò a trovare la mia famiglia.','Forse sabato pioverà.','Abbiamo già deciso la data.','Penso di prenotare una camera.','Ti chiamerò quando arrivo.','Che cosa farai dopo?','L’anno prossimo voglio viaggiare.'],
    comparison:['più','meno','uguale','diverso','migliore','peggiore','alto','veloce','Questo treno è più veloce.','La camera è meno costosa.','Hanno tutti e due la stessa misura.','La mia città è diversa da questa.','Questa opzione è migliore per me.','Oggi il tempo è peggiore di ieri.','Qual è l’edificio più alto?','Preferisco la strada più corta.'],
    ability:['potere','saper fare','avere bisogno','dovere','permesso','vietato','necessario','possibile','Posso farlo da solo.','So cucinare un po’.','Devo uscire presto.','Deve mostrare il passaporto.','Qui si possono fare fotografie.','Qui è vietato fumare.','Posso usare questo posto?','Non sono riuscito a finire in tempo.'],
    services:['prenotazione','ricevuta','conto','riparazione','reso','errore','rotto','soluzione','Ho una prenotazione a mio nome.','Il conto non è corretto.','Questo apparecchio non funziona.','Vorrei cambiare questo prodotto.','Può darmi una ricevuta?','Ho bisogno che lo riparino oggi.','Quando sarà pronto?','Grazie per aver risolto il problema.'],
    conversation:['davvero','certo','forse','allora','inoltre','tuttavia','per questo','capisco','Davvero? Raccontami di più.','Certo, nessun problema.','Forse possiamo andare domani.','Allora ci vediamo alle sei.','Inoltre, devo comprare da mangiare.','Tuttavia, oggi non ho tempo.','Per questo sono arrivato tardi.','Capisco. E dopo che cosa hai fatto?']},
  Russian:{icons:['Вчера','Завтра','↔','Можно','Сервис','Разговор'],
    past:['вчера','вчера вечером','на прошлой неделе','сначала','потом','наконец','произошло','закончилось','Вчера я работал допоздна.','Я пришёл домой в девять.','Сначала я позвонил другу.','Потом мы пошли ужинать.','Я не смог найти ключи.','Что случилось?','Это был интересный опыт.','В конце концов всё закончилось хорошо.'],
    future:['план','намерение','обещание','возможно','точно','следующий','бронировать','решать','Сегодня вечером я буду заниматься.','Завтра я навещу семью.','В субботу, возможно, будет дождь.','Мы уже выбрали дату.','Я собираюсь забронировать номер.','Я позвоню тебе, когда приеду.','Что ты будешь делать потом?','В следующем году я хочу путешествовать.'],
    comparison:['больше','меньше','одинаковый','другой','лучше','хуже','высокий','быстрый','Этот поезд быстрее.','Этот номер дешевле.','Они оба одного размера.','Мой город отличается от этого.','Этот вариант лучше для меня.','Сегодня погода хуже, чем вчера.','Какое здание самое высокое?','Я предпочитаю более короткий путь.'],
    ability:['мочь','уметь','нужно','должен','разрешено','запрещено','необходимо','возможно','Я могу сделать это сам.','Я немного умею готовить.','Мне нужно уйти рано.','Вы должны показать паспорт.','Здесь можно фотографировать.','Здесь нельзя курить.','Можно занять это место?','Я не смог закончить вовремя.'],
    services:['бронь','чек','счёт','ремонт','возврат','ошибка','сломанный','решение','У меня бронь на моё имя.','В счёте ошибка.','Этот прибор не работает.','Я хотел бы обменять этот товар.','Дайте мне чек, пожалуйста.','Мне нужно починить это сегодня.','Когда это будет готово?','Спасибо, что решили проблему.'],
    conversation:['правда','конечно','может быть','тогда','кроме того','однако','поэтому','я понимаю','Правда? Расскажи подробнее.','Конечно, без проблем.','Может быть, мы пойдём завтра.','Тогда увидимся в шесть.','Кроме того, мне нужно купить продукты.','Однако сегодня у меня нет времени.','Поэтому я опоздал.','Я понимаю. А что ты делал потом?']},
  Korean:{icons:['어제','내일','비교','가능','해결','대화'],
    past:['어제','어젯밤','지난주','먼저','그다음','마침내','일어났어요','끝났어요','어제 늦게까지 일했어요.','아홉 시에 집에 도착했어요.','먼저 친구에게 전화했어요.','그다음 같이 저녁을 먹으러 갔어요.','열쇠를 찾을 수 없었어요.','무슨 일이 있었어요?','흥미로운 경험이었어요.','결국 모든 일이 잘됐어요.'],
    future:['계획','의도','약속','아마','확실히','다음','예약하다','결정하다','오늘 밤에 공부할 거예요.','내일 가족을 방문할 거예요.','토요일에는 아마 비가 올 거예요.','날짜를 이미 정했어요.','방을 예약하려고 해요.','도착하면 전화할게요.','그다음에는 무엇을 할 거예요?','내년에는 여행하고 싶어요.'],
    comparison:['더','덜','같다','다르다','더 좋다','더 나쁘다','높다','빠르다','이 기차가 더 빨라요.','그 방이 덜 비싸요.','둘 다 크기가 같아요.','우리 도시는 이곳과 달라요.','이 선택이 저에게 더 좋아요.','오늘 날씨가 어제보다 나빠요.','어느 건물이 가장 높아요?','더 짧은 길로 가고 싶어요.'],
    ability:['할 수 있다','할 줄 알다','필요하다','해야 하다','허용되다','금지되다','필수다','가능하다','혼자 할 수 있어요.','요리를 조금 할 줄 알아요.','일찍 나가야 해요.','여권을 보여 줘야 해요.','여기에서 사진을 찍어도 돼요.','여기에서 담배를 피우면 안 돼요.','이 자리에 앉아도 돼요?','제시간에 끝낼 수 없었어요.'],
    services:['예약','영수증','계산서','수리','반품','오류','고장 난','해결책','제 이름으로 예약했어요.','계산서가 맞지 않아요.','이 기계가 작동하지 않아요.','이 상품을 교환하고 싶어요.','영수증을 주실 수 있어요?','오늘 수리해 주세요.','언제 준비될까요?','문제를 해결해 주셔서 감사합니다.'],
    conversation:['정말','물론','아마','그러면','게다가','하지만','그래서','이해해요','정말요? 더 이야기해 주세요.','물론이죠. 문제없어요.','아마 내일 갈 수 있을 거예요.','그러면 여섯 시에 만나요.','게다가 음식을 사야 해요.','하지만 오늘은 시간이 없어요.','그래서 늦었어요.','이해해요. 그다음에는 무엇을 했어요?']},
  Japanese:{icons:['昨日','明日','比','可','直','話'],
    past:['昨日','昨夜','先週','まず','そのあと','最後に','起こりました','終わりました','昨日は遅くまで働きました。','九時に家に着きました。','まず友達に電話しました。','そのあと、一緒に夕食を食べに行きました。','鍵を見つけることができませんでした。','何がありましたか。','おもしろい経験でした。','最後はすべてうまくいきました。'],
    future:['計画','つもり','約束','たぶん','きっと','次','予約する','決める','今夜勉強するつもりです。','明日は家族に会いに行きます。','土曜日はたぶん雨が降ります。','日付はもう決めました。','部屋を予約するつもりです。','着いたら電話します。','そのあと何をする予定ですか。','来年は旅行したいです。'],
    comparison:['もっと','より少ない','同じ','違う','もっといい','もっと悪い','高い','速い','この電車のほうが速いです。','その部屋のほうが安いです。','二つは同じ大きさです。','私の町はここと違います。','この選択のほうが私にはいいです。','今日は昨日より天気が悪いです。','どの建物がいちばん高いですか。','もっと短い道のほうがいいです。'],
    ability:['できる','やり方を知っている','必要','しなければならない','許可','禁止','必要な','可能','一人でできます。','料理が少しできます。','早く出なければなりません。','パスポートを見せなければなりません。','ここで写真を撮ってもいいです。','ここでたばこを吸ってはいけません。','この席を使ってもいいですか。','時間までに終えることができませんでした。'],
    services:['予約','領収書','請求書','修理','返品','間違い','壊れた','解決','私の名前で予約しています。','請求書が間違っています。','この機械は動きません。','この商品を交換したいです。','領収書をいただけますか。','今日中に修理してください。','いつできますか。','問題を解決してくれてありがとうございます。'],
    conversation:['本当に','もちろん','たぶん','それでは','それに','しかし','だから','分かりました','本当ですか。もっと教えてください。','もちろん、問題ありません。','たぶん明日行けます。','それでは六時に会いましょう。','それに、食べ物を買う必要があります。','しかし、今日は時間がありません。','だから遅れました。','分かりました。そのあと何をしましたか。']},
  Chinese:{icons:['昨','明','比','能','修','谈'],
    past:['昨天','昨天晚上','上个星期','先','然后','最后','发生了','结束了','我昨天工作到很晚。','我九点到家。','我先给朋友打了电话。','然后我们去吃了晚饭。','我没找到钥匙。','发生什么事了？','这是一次有意思的经历。','最后一切都很顺利。'],
    future:['计划','打算','承诺','也许','一定','下一个','预订','决定','我今晚要学习。','我明天会去看家人。','星期六也许会下雨。','我们已经决定日期了。','我打算预订一个房间。','我到了以后给你打电话。','你接下来要做什么？','我明年想去旅行。'],
    comparison:['更','更少','一样','不同','更好','更差','高','快','这列火车更快。','这个房间更便宜。','两个一样大。','我的城市和这里不一样。','这个选择对我更好。','今天的天气比昨天差。','哪座楼最高？','我更喜欢短一点的路。'],
    ability:['能','会','需要','应该','允许','禁止','必要','可能','我能自己做。','我会做一点饭。','我得早点走。','你必须出示护照。','这里可以拍照。','这里不能抽烟。','我可以坐这个座位吗？','我没能按时完成。'],
    services:['预订','收据','账单','修理','退货','错误','坏了','解决办法','我用自己的名字预订了。','账单不对。','这个设备不能用。','我想换这个商品。','可以给我一张收据吗？','我需要今天修好。','什么时候能准备好？','谢谢你解决了这个问题。'],
    conversation:['真的吗','当然','也许','那么','另外','不过','所以','我明白了','真的吗？再多说一点。','当然，没问题。','也许我们明天可以去。','那么我们六点见。','另外，我还要买食物。','不过，我今天没有时间。','所以我迟到了。','我明白了。然后你做了什么？']},
  Portuguese:{icons:['Ontem','Amanhã','↔','Poder','Serviço','Falar'],
    past:['ontem','ontem à noite','na semana passada','primeiro','depois','finalmente','aconteceu','terminou','Ontem trabalhei até tarde.','Cheguei a casa às nove.','Primeiro telefonei ao meu amigo.','Depois fomos jantar.','Não consegui encontrar as chaves.','O que aconteceu?','Foi uma experiência interessante.','No fim, correu tudo bem.'],
    future:['plano','intenção','promessa','talvez','com certeza','próximo','reservar','decidir','Vou estudar esta noite.','Amanhã vou visitar a minha família.','Talvez chova no sábado.','Já decidimos a data.','Penso reservar um quarto.','Telefono-te quando chegar.','O que vais fazer depois?','No próximo ano quero viajar.'],
    comparison:['mais','menos','igual','diferente','melhor','pior','alto','rápido','Este comboio é mais rápido.','O quarto é menos caro.','Os dois têm o mesmo tamanho.','A minha cidade é diferente desta.','Esta opção é melhor para mim.','Hoje o tempo está pior do que ontem.','Qual é o edifício mais alto?','Prefiro o caminho mais curto.'],
    ability:['poder','saber fazer','precisar','dever','permitido','proibido','necessário','possível','Consigo fazer isto sozinho.','Sei cozinhar um pouco.','Tenho de sair cedo.','Tem de mostrar o passaporte.','Aqui pode tirar fotografias.','Aqui não se pode fumar.','Posso usar este lugar?','Não consegui terminar a tempo.'],
    services:['reserva','recibo','conta','reparação','devolução','erro','avariado','solução','Tenho uma reserva em meu nome.','A conta não está certa.','Este aparelho não funciona.','Gostaria de trocar este produto.','Pode dar-me um recibo?','Preciso que o reparem hoje.','Quando estará pronto?','Obrigado por resolver o problema.'],
    conversation:['a sério','claro','talvez','então','além disso','no entanto','por isso','compreendo','A sério? Conta-me mais.','Claro, não há problema.','Talvez possamos ir amanhã.','Então encontramo-nos às seis.','Além disso, preciso de comprar comida.','No entanto, hoje não tenho tempo.','Por isso cheguei tarde.','Compreendo. E o que fizeste depois?']},
  Arabic:{icons:['أمس','غدًا','فرق','قدرة','حل','حديث'],
    past:['أمس','البارحة','الأسبوع الماضي','أولًا','بعد ذلك','أخيرًا','حدث','انتهى','عملت حتى وقت متأخر أمس.','وصلت إلى البيت في التاسعة.','أولًا اتصلت بصديقي.','بعد ذلك ذهبنا لتناول العشاء.','لم أستطع أن أجد مفاتيحي.','ماذا حدث؟','كانت تجربة ممتعة.','في النهاية سار كل شيء على ما يرام.'],
    future:['خطة','نية','وعد','ربما','بالتأكيد','القادم','يحجز','يقرر','سأدرس هذه الليلة.','سأزور عائلتي غدًا.','ربما تمطر يوم السبت.','لقد قررنا التاريخ بالفعل.','أنوي حجز غرفة.','سأتصل بك عندما أصل.','ماذا ستفعل بعد ذلك؟','أريد أن أسافر في العام القادم.'],
    comparison:['أكثر','أقل','نفسه','مختلف','أفضل','أسوأ','مرتفع','سريع','هذا القطار أسرع.','هذه الغرفة أقل تكلفة.','كلاهما بالحجم نفسه.','مدينتي مختلفة عن هذه المدينة.','هذا الخيار أفضل لي.','الطقس اليوم أسوأ من الأمس.','أي مبنى هو الأعلى؟','أفضل الطريق الأقصر.'],
    ability:['يستطيع','يعرف كيف','يحتاج','يجب','مسموح','ممنوع','ضروري','ممكن','أستطيع أن أفعل ذلك وحدي.','أعرف كيف أطبخ قليلًا.','يجب أن أخرج مبكرًا.','يجب أن تُظهر جواز سفرك.','يُسمح بالتصوير هنا.','التدخين ممنوع هنا.','هل يمكنني استخدام هذا المقعد؟','لم أستطع الانتهاء في الوقت المحدد.'],
    services:['حجز','إيصال','فاتورة','إصلاح','إرجاع','خطأ','مكسور','حل','لدي حجز باسمي.','الفاتورة غير صحيحة.','هذا الجهاز لا يعمل.','أود استبدال هذا المنتج.','هل يمكن أن تعطيني إيصالًا؟','أحتاج إلى إصلاحه اليوم.','متى سيكون جاهزًا؟','شكرًا لحل المشكلة.'],
    conversation:['حقًا','بالطبع','ربما','إذن','بالإضافة إلى ذلك','لكن','لذلك','أفهم','حقًا؟ أخبرني بالمزيد.','بالطبع، لا مشكلة.','ربما نستطيع الذهاب غدًا.','إذن نلتقي في السادسة.','بالإضافة إلى ذلك، أحتاج إلى شراء الطعام.','لكن ليس لدي وقت اليوم.','لذلك وصلت متأخرًا.','أفهم. وماذا فعلت بعد ذلك؟']},
});

export function validateA21Content(){
  for(const[language,payload]of Object.entries(A21_TARGETS)){
    if(!Array.isArray(payload.icons)||payload.icons.length!==A21_THEMES.length)throw new Error(`${language}: iconos A2.1 incompletos`);
    const all=[];
    for(const theme of A21_THEMES){
      if(!Array.isArray(payload[theme.id])||payload[theme.id].length!==theme.meanings.length)throw new Error(`${language}/${theme.id}: se esperaban ${theme.meanings.length} contenidos`);
      if(payload[theme.id].some(value=>!String(value).trim()))throw new Error(`${language}/${theme.id}: texto vacío`);
      if(new Set(payload[theme.id]).size!==payload[theme.id].length)throw new Error(`${language}/${theme.id}: objetivos duplicados dentro de la unidad`);
      all.push(...payload[theme.id]);
    }
    // La recuperación intencional entre unidades está permitida; cada unidad
    // sigue aportando al menos ocho audios realmente nuevos.
  }
  return true;
}
