import{authService}from'./auth_service.js';
import{SyncService}from'./sync_service.js';
import{exportProgress,saveBackup,validateImport,writeSnapshot}from'./local_progress_store.js';

const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const formatDate=value=>{if(!value||value==='Sin actividad')return'Sin actividad';const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'});};

export class AccountUI{
  constructor({button,onCheckUpdates}){this.button=button;this.onCheckUpdates=onCheckUpdates;this.sync=new SyncService(authService);this.dialog=document.createElement('dialog');this.dialog.id='account-dialog';this.dialog.className='account-dialog';document.body.append(this.dialog);this.importInput=document.createElement('input');this.importInput.type='file';this.importInput.accept='application/json,.json';this.importInput.hidden=true;document.body.append(this.importInput);this.button.addEventListener('click',()=>this.open());this.dialog.addEventListener('click',event=>this.handleClick(event));this.importInput.addEventListener('change',event=>this.importFile(event));this.boundChange=()=>this.render();}
  async start(){authService.addEventListener('change',this.boundChange);this.sync.addEventListener('change',this.boundChange);this.sync.addEventListener('account-choice',this.boundChange);await authService.init();await this.sync.init();this.render();return this;}
  open(){this.render();this.dialog.showModal();}
  statusLabel(){return({device:'Guardado solo en este dispositivo',choice:'Elige qué progreso quieres usar',syncing:'Sincronizando…',synced:'Sincronizado',offline:'Sin conexión: cambios pendientes',error:'Error de sincronización'}[this.sync.status]||'Preparando cuenta…');}
  render(){const session=authService.session,user=session?.user,meta=user?.user_metadata||{},choice=this.sync.pendingChoice,configured=authService.configured;this.button.textContent=user?'Mi cuenta':'Cuenta';this.button.classList.toggle('account-signed-in',Boolean(user));this.dialog.innerHTML=`<form method="dialog" class="account-panel"><button class="account-close" value="close" aria-label="Cerrar">×</button><span class="eyebrow">CUENTA Y PROGRESO</span><h2>${user?'Tu cuenta HanStory':'Protege tu progreso'}</h2>${user?`<section class="account-person"><img src="${esc(meta.avatar_url||meta.picture||'./assets/icon-192.svg')}" alt=""><div><strong>${esc(meta.full_name||meta.name||'Usuario')}</strong><span>${esc(user.email||'')}</span></div></section>`:`<p>Estudia sin cuenta o inicia sesión para respaldar y sincronizar tu avance entre dispositivos.</p>`}${!user&&!configured?'<p class="account-config-note">El inicio de sesión se activará cuando agregues los dos valores públicos de Supabase. El modo sin cuenta ya funciona.</p>':''}<section class="sync-state ${esc(this.sync.status)}"><i></i><div><strong>${esc(this.statusLabel())}</strong><span>${this.sync.lastSync?`Última sincronización: ${esc(formatDate(this.sync.lastSync))}`:'Todavía no se ha sincronizado'} · <b id="pending-count">0</b> cambios pendientes</span>${this.sync.error?`<small>${esc(this.sync.error)}</small>`:''}</div></section>${choice?this.choiceHTML(choice):''}<div class="account-actions">${!user?`<button type="button" class="google-login" data-account-action="google" ${configured?'':'disabled'}>Continuar con Google</button><button type="button" data-account-action="guest">Continuar sin cuenta</button>`:`<button type="button" class="primary" data-account-action="sync">Sincronizar ahora</button><button type="button" data-account-action="logout">Cerrar sesión</button>`}<button type="button" data-account-action="export">Exportar progreso</button><button type="button" data-account-action="import">Importar progreso</button><button type="button" data-account-action="updates">Buscar actualizaciones</button></div><p class="account-privacy">HanStory solicita únicamente identidad básica: nombre, correo y avatar. No solicita acceso a Gmail, Drive, contactos ni calendario.</p></form>`;this.sync.pendingCount().then(count=>{const target=this.dialog.querySelector('#pending-count');if(target)target.textContent=count;});}
  choiceHTML(choice){const summary=(title,value)=>`<div><strong>${title}</strong><span>${value.xp} XP</span><span>${value.completedLessons} lecciones completadas</span><span>${esc(formatDate(value.lastActivity))}</span></div>`;return`<section class="account-merge"><h3>Encontramos progreso en este dispositivo</h3><div class="account-compare">${summary('Progreso local',choice.localSummary)}${summary('Progreso en la nube',choice.cloudSummary)}</div><p>Antes de reemplazar algo se guardará una copia local.</p><div><button type="button" class="primary" data-merge="combine">Combinar progresos</button><button type="button" data-merge="local">Usar progreso local</button><button type="button" data-merge="cloud">Usar progreso de la nube</button><button type="button" data-merge="cancel">Cancelar</button></div></section>`;}
  async handleClick(event){const merge=event.target.closest('[data-merge]'),action=event.target.closest('[data-account-action]');try{if(merge){merge.disabled=true;await this.sync.resolveAccountProgress(merge.dataset.merge);return;}if(!action)return;action.disabled=true;if(action.dataset.accountAction==='google')await authService.signInWithGoogle();else if(action.dataset.accountAction==='guest')this.dialog.close();else if(action.dataset.accountAction==='sync')await this.sync.flush();else if(action.dataset.accountAction==='logout'){await this.sync.prepareSignOut();await authService.signOut();location.reload();}else if(action.dataset.accountAction==='export')await this.exportFile();else if(action.dataset.accountAction==='import')this.importInput.click();else if(action.dataset.accountAction==='updates')await this.onCheckUpdates?.();}catch(error){this.sync.fail(error);this.render();}finally{action.disabled=false;}}
  async exportFile(){const payload=await exportProgress(),blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=`hanstory-progreso-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000);}
  async importFile(event){const file=event.target.files?.[0];if(!file)return;try{const records=validateImport(JSON.parse(await file.text()));await saveBackup('antes-de-importar');await writeSnapshot(records,{clear:true,sync:false});for(const record of records)await this.sync.enqueue(record,authService.session?.user?.id||null);await this.sync.flush();location.reload();}catch(error){this.sync.fail(error);this.render();}finally{event.target.value='';}}
}
