import{authService}from'./auth_service.js';
import{SyncService}from'./sync_service.js';
import{exportProgress,saveBackup,validateImport,writeSnapshot}from'./local_progress_store.js';
import{xpService}from'./xp_service.js';
import{friendsService,normalizeFriendCode}from'./friends_service.js';

const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const formatDate=value=>{if(!value||value==='Sin actividad')return'Sin actividad';const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'});};
const languageNames={japanese:'Japonés',korean:'Coreano',english:'Inglés',french:'Francés',german:'Alemán',italian:'Italiano',russian:'Ruso',chinese:'Chino',portuguese:'Portugués',arabic:'Árabe'};
const byLanguageHTML=summary=>{const entries=Object.entries(summary?.byLanguage||{}).sort((a,b)=>b[1]-a[1]);if(!entries.length)return'<p class="account-empty">Completa una lección para comenzar a ganar XP.</p>';const max=Math.max(...entries.map(([,xp])=>Number(xp)||0),1);return`<div class="xp-language-list">${entries.map(([language,xp])=>`<div><span><b>${esc(languageNames[language]||language)}</b><em>${Number(xp).toLocaleString()} XP</em></span><i><u style="width:${Number(xp)/max*100}%"></u></i></div>`).join('')}</div>`;};

export class AccountUI{
  constructor({button,onCheckUpdates}){this.button=button;this.onCheckUpdates=onCheckUpdates;this.sync=new SyncService(authService);this.tab='account';this.xpSummary={totalXp:0,byLanguage:{},pendingXp:0};this.dialog=document.createElement('dialog');this.dialog.id='account-dialog';this.dialog.className='account-dialog';document.body.append(this.dialog);this.importInput=document.createElement('input');this.importInput.type='file';this.importInput.accept='application/json,.json';this.importInput.hidden=true;document.body.append(this.importInput);this.button.addEventListener('click',()=>this.open());this.dialog.addEventListener('click',event=>this.handleClick(event));this.dialog.addEventListener('submit',event=>this.handleSubmit(event));this.importInput.addEventListener('change',event=>this.importFile(event));this.boundChange=()=>this.refreshView();}
  async start(){authService.addEventListener('change',this.boundChange);this.sync.addEventListener('change',this.boundChange);this.sync.addEventListener('account-choice',this.boundChange);xpService.addEventListener('change',this.boundChange);friendsService.addEventListener('change',this.boundChange);await authService.init();await this.sync.init();await xpService.init();if(authService.session?.user){await xpService.claimGuestEvents();await xpService.flush();}await friendsService.init();await this.refreshXp();this.render();return this;}
  open(){this.render();this.dialog.showModal();this.refreshXp();if(authService.session?.user&&navigator.onLine)friendsService.refresh();}
  async refreshXp(){this.xpSummary=await xpService.getSummary().catch(()=>this.xpSummary);this.updateDynamic();}
  refreshView(){this.refreshXp();if(this.dialog.open)this.render();}
  statusLabel(){return({device:'Guardado solo en este dispositivo',choice:'Elige qué progreso quieres usar',syncing:'Sincronizando…',synced:'Sincronizado',offline:'Sin conexión: cambios pendientes',error:'Error de sincronización'}[this.sync.status]||'Preparando cuenta…');}
  tabsHTML(active){return`<nav class="account-tabs" aria-label="Secciones de cuenta">${[['account','Cuenta'],['progress','Progreso'],['friends','Amigos'],['requests','Solicitudes']].map(([id,label])=>`<button type="button" data-account-tab="${id}" class="${active===id?'active':''}">${label}${id==='requests'&&friendsService.requests.received?.length?` <b>${friendsService.requests.received.length}</b>`:''}</button>`).join('')}</nav>`;}
  render(){const user=authService.session?.user,meta=user?.user_metadata||{},choice=this.sync.pendingChoice,configured=authService.configured;this.button.textContent=user?'Mi cuenta':'Cuenta';this.button.classList.toggle('account-signed-in',Boolean(user));this.dialog.innerHTML=`<div class="account-panel account-panel-wide"><button type="button" class="account-close" data-account-action="close" aria-label="Cerrar">×</button><span class="eyebrow">HANSTORY</span><h2>${user?'Tu cuenta y comunidad':'Protege tu progreso'}</h2>${user?this.tabsHTML(this.tab):''}${choice?this.choiceHTML(choice):''}<div class="account-tab-content">${user?this.userTab(this.tab,user,meta):this.guestHTML(configured)}</div></div>`;this.updateDynamic();}
  userTab(tab,user,meta){if(tab==='progress')return this.progressHTML();if(tab==='friends')return this.friendsHTML();if(tab==='requests')return this.requestsHTML();const profile=friendsService.profile||{},friendCode=profile.friend_code||'—';return`<section class="account-person"><img src="${esc(meta.avatar_url||meta.picture||'./assets/icon-192.svg')}" alt=""><div><strong>${esc(meta.full_name||meta.name||'Usuario')}</strong><span>${esc(user.email||'')}</span></div></section><section class="friend-code-card"><span>Mi código de amigo</span><strong>${esc(friendCode)}</strong><button type="button" data-account-action="copy-code" ${friendCode==='—'?'disabled':''}>Copiar código</button><small>Es único, privado para compartir e inmutable.</small></section>${this.syncHTML()}<div class="account-actions"><button type="button" class="primary" data-account-action="sync">Sincronizar ahora</button><button type="button" data-account-action="export">Exportar progreso</button><button type="button" data-account-action="import">Importar progreso</button><button type="button" data-account-action="updates">Buscar actualizaciones</button><button type="button" data-account-action="logout">Cerrar sesión</button></div><p class="account-privacy">Solo tú ves tu correo. Tus amigos ven nombre, avatar, código y XP agregado; nunca tus respuestas, errores, correo o identificador interno.</p>`;}
  guestHTML(configured){return`<p>Estudia sin cuenta o inicia sesión para respaldar tu avance, sumar XP entre idiomas y agregar amigos.</p>${!configured?'<p class="account-config-note">Las cuentas no están disponibles en este momento. Puedes seguir estudiando y tu progreso permanecerá guardado en este dispositivo.</p>':''}${this.syncHTML()}<div class="account-actions"><button type="button" class="google-login" data-account-action="google" ${configured?'':'disabled'}>Continuar con Google</button><button type="button" data-account-action="guest">Continuar sin cuenta</button><button type="button" data-account-action="export">Exportar progreso</button><button type="button" data-account-action="import">Importar progreso</button></div><p class="account-privacy">HanStory solicita únicamente identidad básica: nombre, correo y avatar. No solicita Gmail, Drive, contactos ni calendario.</p>`;}
  syncHTML(){return`<section class="sync-state ${esc(this.sync.status)}"><i></i><div><strong>${esc(this.statusLabel())}</strong><span>${this.sync.lastSync?`Última sincronización: ${esc(formatDate(this.sync.lastSync))}`:'Todavía no se ha sincronizado'} · <b id="pending-count">0</b> cambios pendientes</span>${this.sync.error?`<small>${esc(this.sync.error)}</small>`:''}${xpService.error?`<small>${esc(xpService.error)}</small>`:''}</div></section>`;}
  progressHTML(){const s=this.xpSummary;return`<section class="xp-summary"><div><span>XP total</span><strong data-total-xp>${Number(s.totalXp||0).toLocaleString()}</strong><small>${Number(s.pendingXp||0)?`${s.pendingXp} XP pendientes de sincronizar`:'Confirmado y guardado'}</small></div><div><span>XP de hoy</span><strong>${Number(s.todayXp||0).toLocaleString()}</strong><small>Última actividad: ${esc(formatDate(s.lastActivity))}</small></div><div><span>Lecciones completadas</span><strong>${Number(s.completedLessons||0).toLocaleString()}</strong><small>Sin contar aperturas ni simples visitas</small></div></section><h3>XP por idioma</h3>${byLanguageHTML(s)}<p class="account-note">Una lección solo concede su recompensa completa la primera vez. Repetirla no duplica XP.</p>`;}
  friendsHTML(){if(!navigator.onLine)return'<div class="account-empty"><h3>Amigos no está disponible sin conexión</h3><p>Necesitas conexión para agregar o administrar amigos.</p></div>';const lookup=friendsService.lookup,error=friendsService.error?`<p class="account-error">${esc(friendsService.error)}</p>`:'';return`${error}<section class="friend-add"><h3>Agregar por código</h3><form data-friend-search><input name="friendCode" autocomplete="off" placeholder="HS-7K4P9Q" maxlength="10" aria-label="Código de amigo"><button class="primary">Buscar</button></form>${lookup?`<article class="friend-preview"><img src="${esc(lookup.avatar_url||'./assets/icon-192.svg')}" alt=""><div><strong>${esc(lookup.display_name||'Usuario HanStory')}</strong><span>${esc(lookup.friend_code)}</span></div><button type="button" data-send-friend="${esc(lookup.friend_code)}">Enviar solicitud</button></article>`:''}</section><h3>Mis amigos</h3>${friendsService.friends.length?`<div class="friend-list">${friendsService.friends.map(friend=>this.friendCard(friend)).join('')}</div>`:'<div class="account-empty"><h3>Aún no tienes amigos</h3><p>Comparte tu código para que puedan agregarte.</p></div>'}`;}
  friendCard(friend){const top=Object.entries(friend.by_language||{}).sort((a,b)=>b[1]-a[1])[0];return`<details class="friend-card"><summary><img src="${esc(friend.avatar_url||'./assets/icon-192.svg')}" alt=""><div><strong>${esc(friend.display_name||'Usuario HanStory')}</strong><span>${Number(friend.total_xp||0).toLocaleString()} XP${top?` · ${esc(languageNames[top[0]]||top[0])}`:''}</span></div><b>Ver perfil</b></summary><div><code>${esc(friend.friend_code)}</code>${byLanguageHTML({byLanguage:friend.by_language||{}})}<small>Última actividad aproximada: ${esc(formatDate(friend.last_activity))}</small><button type="button" data-remove-friend="${esc(friend.friend_code)}">Eliminar amistad</button></div></details>`;}
  requestsHTML(){if(!navigator.onLine)return'<div class="account-empty"><h3>Solicitudes no está disponible sin conexión</h3><p>Conéctate para aceptar, rechazar o cancelar solicitudes.</p></div>';const received=friendsService.requests.received||[],sent=friendsService.requests.sent||[],error=friendsService.error?`<p class="account-error">${esc(friendsService.error)}</p>`:'';return`${error}<h3>Recibidas</h3>${received.length?received.map(item=>this.requestCard(item,'received')).join(''):'<p class="account-empty">No tienes solicitudes recibidas.</p>'}<h3>Enviadas</h3>${sent.length?sent.map(item=>this.requestCard(item,'sent')).join(''):'<p class="account-empty">No tienes solicitudes enviadas.</p>'}`;}
  requestCard(item,direction){return`<article class="friend-request"><img src="${esc(item.avatar_url||'./assets/icon-192.svg')}" alt=""><div><strong>${esc(item.display_name||'Usuario HanStory')}</strong><span>${esc(item.friend_code)}</span></div><div>${direction==='received'?`<button type="button" class="primary" data-request-action="accepted" data-request-id="${esc(item.request_id)}">Aceptar</button><button type="button" data-request-action="rejected" data-request-id="${esc(item.request_id)}">Rechazar</button>`:`<button type="button" data-request-action="cancel" data-request-id="${esc(item.request_id)}">Cancelar</button>`}</div></article>`;}
  choiceHTML(choice){const summary=(title,value)=>`<div><strong>${title}</strong><span>${value.xp} XP</span><span>${value.completedLessons} lecciones completadas</span><span>${esc(formatDate(value.lastActivity))}</span></div>`;return`<section class="account-merge"><h3>Encontramos progreso en este dispositivo</h3><div class="account-compare">${summary('Progreso local',choice.localSummary)}${summary('Progreso en la nube',choice.cloudSummary)}</div><p>Antes de reemplazar algo se guardará una copia local.</p><div><button type="button" class="primary" data-merge="combine">Combinar progresos</button><button type="button" data-merge="local">Usar progreso local</button><button type="button" data-merge="cloud">Usar progreso de la nube</button><button type="button" data-merge="cancel">Cancelar</button></div></section>`;}
  async updateDynamic(){this.sync.pendingCount().then(count=>{const target=this.dialog.querySelector('#pending-count');if(target)target.textContent=count;});const total=this.dialog.querySelector('[data-total-xp]');if(total)total.textContent=Number(this.xpSummary.totalXp||0).toLocaleString();}
  async handleSubmit(event){if(!event.target.matches('[data-friend-search]'))return;event.preventDefault();const input=event.target.elements.friendCode;try{await friendsService.find(normalizeFriendCode(input.value));this.render();}catch(error){friendsService.error=error.message;this.showError(error);}}
  async handleClick(event){const tab=event.target.closest('[data-account-tab]'),merge=event.target.closest('[data-merge]'),action=event.target.closest('[data-account-action]'),send=event.target.closest('[data-send-friend]'),remove=event.target.closest('[data-remove-friend]'),request=event.target.closest('[data-request-action]');try{if(tab){this.tab=tab.dataset.accountTab;this.render();if(['friends','requests'].includes(this.tab)&&navigator.onLine)friendsService.refresh();return;}if(merge){merge.disabled=true;const strategy=merge.dataset.merge;if(['combine','local'].includes(strategy))await xpService.claimGuestEvents();await this.sync.resolveAccountProgress(strategy);if(strategy!=='cancel'){await xpService.refreshRemote();await xpService.flush();}return;}if(send){send.disabled=true;await friendsService.send(send.dataset.sendFriend);this.render();return;}if(remove){if(!confirm('¿Eliminar esta amistad?'))return;await friendsService.remove(remove.dataset.removeFriend);this.render();return;}if(request){request.disabled=true;if(request.dataset.requestAction==='cancel')await friendsService.cancel(request.dataset.requestId);else await friendsService.respond(request.dataset.requestId,request.dataset.requestAction);this.render();return;}if(!action)return;action.disabled=true;if(action.dataset.accountAction==='close')this.dialog.close();else if(action.dataset.accountAction==='google')await authService.signInWithGoogle();else if(action.dataset.accountAction==='guest')this.dialog.close();else if(action.dataset.accountAction==='sync'){await this.sync.flush();await xpService.refreshRemote();await xpService.flush();await friendsService.refresh();}else if(action.dataset.accountAction==='logout'){await this.sync.prepareSignOut();await authService.signOut();location.reload();}else if(action.dataset.accountAction==='copy-code')await navigator.clipboard.writeText(friendsService.profile?.friend_code||'');else if(action.dataset.accountAction==='export')await this.exportFile();else if(action.dataset.accountAction==='import')this.importInput.click();else if(action.dataset.accountAction==='updates')await this.onCheckUpdates?.();}catch(error){this.sync.fail(error);this.showError(error);}finally{if(action)action.disabled=false;}}
  showError(error){const content=this.dialog.querySelector('.account-tab-content');if(content)content.insertAdjacentHTML('afterbegin',`<p class="account-error">${esc(error.message||error)}</p>`);}
  async exportFile(){const payload=await exportProgress(),blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=`hanstory-progreso-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000);}
  async importFile(event){const file=event.target.files?.[0];if(!file)return;try{const records=validateImport(JSON.parse(await file.text()));await saveBackup('antes-de-importar');await writeSnapshot(records,{clear:true,sync:false});for(const record of records)await this.sync.enqueue(record,authService.session?.user?.id||null);await this.sync.flush();location.reload();}catch(error){this.sync.fail(error);this.render();}finally{event.target.value='';}}
}
