import{mergeProgressData}from'./progress_merge.js';

export class CloudProgressStore{
  constructor(auth){this.auth=auth;}
  get client(){return this.auth.client;}
  async loadAll(userId){if(!this.client||!userId)return[];const{data,error}=await this.client.from('user_progress').select('progress_key,progress_data,client_updated_at,server_updated_at').eq('user_id',userId);if(error)throw error;return(data||[]).map(row=>({...row.progress_data,entityKey:row.progress_key,updatedAt:row.client_updated_at||row.server_updated_at}));}
  async loadOne(userId,entityKey){if(!this.client)return null;const{data,error}=await this.client.from('user_progress').select('progress_data,client_updated_at,server_updated_at').eq('user_id',userId).eq('progress_key',entityKey).maybeSingle();if(error)throw error;return data?{...data.progress_data,entityKey,updatedAt:data.client_updated_at||data.server_updated_at}:null;}
  async applyEvent(userId,event){if(!this.client)throw new Error('La nube no está configurada.');const eventRow={event_id:event.eventId,user_id:userId,device_id:event.deviceId,entity_key:event.entityKey,event_type:event.eventType,payload:event.payload,client_created_at:event.clientUpdatedAt};const eventResult=await this.client.from('sync_events').upsert(eventRow,{onConflict:'event_id',ignoreDuplicates:true});if(eventResult.error)throw eventResult.error;if(event.eventType==='delete'){const deletion=await this.client.from('user_progress').delete().eq('user_id',userId).eq('progress_key',event.entityKey);if(deletion.error)throw deletion.error;return null;}const remote=await this.loadOne(userId,event.entityKey),incoming=event.payload,merged=remote?{...incoming,value:mergeProgressData(incoming.value||{},remote.value||{}),updatedAt:[incoming.updatedAt,remote.updatedAt].filter(Boolean).sort().at(-1)}:incoming;const result=await this.client.from('user_progress').upsert({user_id:userId,progress_key:event.entityKey,schema_version:1,progress_data:merged,client_updated_at:merged.updatedAt||event.clientUpdatedAt},{onConflict:'user_id,progress_key'});if(result.error)throw result.error;return merged;}
}
