export const JAPANESE_PROGRESS_ID='jp-guided-progress-v1';
export const JAPANESE_PASSING_SCORE=85;
export const JAPANESE_MASTERY_SCORE=95;
const DAY=86400000;
export function defaultJapaneseProgress(){return{id:JAPANESE_PROGRESS_ID,courseVersion:4,language:'Japanese',xp:0,currentUnit:'hiragana-01',currentLesson:'jp-hira-01-family-1',completedLessons:[],lessonScores:{},masteryByItem:{},mistakes:[],reviewDue:[],activityDates:[],streak:0,lastStudyDate:null,unlockedUnits:['hiragana-01'],unlockedLessons:['jp-hira-01-family-1']};}
export function normalizeJapaneseProgress(value={}){const base=defaultJapaneseProgress();return{...base,...value,id:JAPANESE_PROGRESS_ID,language:'Japanese',completedLessons:[...(value.completedLessons||[])],lessonScores:{...(value.lessonScores||{})},masteryByItem:{...(value.masteryByItem||{})},mistakes:[...(value.mistakes||[])],reviewDue:[...(value.reviewDue||[])],activityDates:[...(value.activityDates||[])],unlockedUnits:[...(value.unlockedUnits||base.unlockedUnits)],unlockedLessons:[...(value.unlockedLessons||base.unlockedLessons)]};}
export function migrateJapaneseProgress(value,units=[],courseVersion=defaultJapaneseProgress().courseVersion){const next=normalizeJapaneseProgress(value||{}),ordered=units.filter(Boolean),unitIds=new Set(ordered.map(unit=>unit.id)),lessons=ordered.flatMap(unit=>(unit.lessons||[]).map(lesson=>({unit,lesson}))),lessonIds=new Set(lessons.map(item=>item.lesson.id)),activityIds=new Set(lessons.flatMap(item=>(item.lesson.activities||[]).map(activity=>activity.id))),firstUnit=ordered[0],firstLesson=firstUnit?.lessons?.[0];next.courseVersion=courseVersion;next.completedLessons=[...new Set(next.completedLessons.filter(id=>lessonIds.has(id)))];next.lessonScores=Object.fromEntries(Object.entries(next.lessonScores).filter(([id])=>lessonIds.has(id)));next.masteryByItem=Object.fromEntries(Object.entries(next.masteryByItem).filter(([id])=>activityIds.has(id)));next.mistakes=next.mistakes.filter(item=>lessonIds.has(item.lessonId)&&activityIds.has(item.activityId));next.reviewDue=next.mistakes.map(item=>item.dueAt);next.unlockedUnits=[...new Set(next.unlockedUnits.filter(id=>unitIds.has(id)))];next.unlockedLessons=[...new Set(next.unlockedLessons.filter(id=>lessonIds.has(id)))];if(firstUnit&&!next.unlockedUnits.includes(firstUnit.id))next.unlockedUnits.unshift(firstUnit.id);if(firstLesson&&!next.unlockedLessons.includes(firstLesson.id))next.unlockedLessons.unshift(firstLesson.id);for(const unit of ordered){const unitFirst=unit.lessons?.[0];if(unitFirst&&next.unlockedUnits.includes(unit.id)&&!next.unlockedLessons.includes(unitFirst.id))next.unlockedLessons.push(unitFirst.id);for(let index=0;index<(unit.lessons||[]).length-1;index++)if(next.completedLessons.includes(unit.lessons[index].id)&&!next.unlockedLessons.includes(unit.lessons[index+1].id))next.unlockedLessons.push(unit.lessons[index+1].id);}const current=lessons.find(item=>item.lesson.id===next.currentLesson),fallback=lessons.find(item=>next.unlockedLessons.includes(item.lesson.id)&&!next.completedLessons.includes(item.lesson.id))||lessons.find(item=>next.unlockedLessons.includes(item.lesson.id))||lessons[0];next.currentLesson=(current||fallback)?.lesson.id||'';next.currentUnit=(current||fallback)?.unit.id||firstUnit?.id||'';return next;}
export function parseJapaneseRoute(hash=''){const clean=String(hash).replace(/^#/,'').replace(/^\//,'').split('?')[0],parts=clean.split('/').filter(Boolean);if(parts[0]!=='japanese')return null;if(parts[1]==='review')return{name:'review'};if(parts[1]==='profile')return{name:'profile'};if(parts[1]!=='course'||parts.length===2)return{name:'course'};if(parts[2]==='unit'&&parts[3])return{name:'unit',id:decodeURIComponent(parts[3])};if(parts[2]==='lesson'&&parts[3])return{name:'lesson',id:decodeURIComponent(parts[3])};if(parts[2]==='result'&&parts[3])return{name:'result',id:decodeURIComponent(parts[3])};return{name:'course'};}
export function lessonStatus(lesson,index,progress){if(progress.completedLessons.includes(lesson.id)){const score=progress.lessonScores[lesson.id]?.percentage||0;return score>=JAPANESE_MASTERY_SCORE?'mastered':'completed';}if(progress.mistakes.some(item=>item.lessonId===lesson.id&&new Date(item.dueAt)<=new Date()))return'review_due';if(progress.currentLesson===lesson.id)return'in_progress';if(progress.unlockedLessons.includes(lesson.id)||index===0)return'available';return'locked';}
export function isGradableActivity(activity){return activity.gradable!==false&&!['lesson_intro','teach_kana','teach_concept','teach_word','teach_pattern','teach_kanji','dialogue_model'].includes(activity.type);}
export function scoreActivities(activities,answers){let correct=0,xp=activities.filter(activity=>!isGradableActivity(activity)).reduce((sum,activity)=>sum+Number(activity.xp||0),0);const errors=[],graded=activities.filter(isGradableActivity);graded.forEach(activity=>{const given=answers[activity.id]??'';if(String(given)===String(activity.answer)){correct++;xp+=Number(activity.xp||0);}else errors.push({activityId:activity.id,tags:activity.tags||[],answer:activity.answer,given,activity});});return{correct,total:graded.length,errors,xp,percentage:graded.length?Math.round(correct/graded.length*100):100};}
function dateKey(date){return new Date(date).toISOString().slice(0,10);}
export function completeJapaneseLesson(progress,unit,lesson,result,now=new Date()){const next=normalizeJapaneseProgress(progress),lessonIndex=unit.lessons.findIndex(item=>item.id===lesson.id),passed=result.percentage>=JAPANESE_PASSING_SCORE,previousScore=next.lessonScores[lesson.id]||{};if(!next.completedLessons.includes(lesson.id)&&passed)next.completedLessons.push(lesson.id);next.lessonScores[lesson.id]={percentage:Math.max(Number(previousScore.percentage||0),result.percentage),correct:Math.max(Number(previousScore.correct||0),result.correct),total:result.total,xp:Math.max(Number(previousScore.xp||0),result.xp),completedAt:now.toISOString()};for(const activity of lesson.activities){const ok=!result.errors.some(error=>error.activityId===activity.id),old=next.masteryByItem[activity.id]||{correct:0,wrong:0,stage:0};next.masteryByItem[activity.id]={correct:old.correct+(ok?1:0),wrong:old.wrong+(ok?0:1),stage:ok?Math.min(4,old.stage+1):0,lastSeen:now.toISOString()};next.mistakes=next.mistakes.filter(item=>item.activityId!==activity.id);if(!ok)next.mistakes.push({activityId:activity.id,lessonId:lesson.id,unitId:unit.id,dueAt:new Date(now.getTime()+DAY).toISOString(),stage:0,activity});}
const nextLesson=unit.lessons[lessonIndex+1];if(passed&&nextLesson&&!next.unlockedLessons.includes(nextLesson.id))next.unlockedLessons.push(nextLesson.id);next.currentLesson=passed&&nextLesson?nextLesson.id:lesson.id;next.currentUnit=unit.id;const today=dateKey(now),yesterday=dateKey(new Date(now.getTime()-DAY));next.streak=next.lastStudyDate===today?next.streak:next.lastStudyDate===yesterday?next.streak+1:1;next.lastStudyDate=today;if(!next.activityDates.includes(today))next.activityDates.push(today);next.reviewDue=next.mistakes.map(item=>item.dueAt);return next;}
export function reviewsDue(progress,now=new Date()){return normalizeJapaneseProgress(progress).mistakes.filter(item=>new Date(item.dueAt)<=now);}
export function coursePercent(units,progress){const lessons=units.flatMap(unit=>unit.lessons||[]);return lessons.length?Math.round(progress.completedLessons.filter(id=>lessons.some(lesson=>lesson.id===id)).length/lessons.length*100):0;}
