const DB_NAME='hanstory-player', DB_VERSION=2;
const BASE_STORES=['progress','downloads','localBooks','metadata'];
const listeners=new Set();
let dbPromise=null;

export function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);let settled=false;const fail=error=>{if(settled)return;settled=true;dbPromise=null;reject(error);};const blockedTimer=setTimeout(()=>fail(new Error('Otra pestaña está usando una versión anterior del progreso.')),1500);request.onblocked=()=>{};request.onupgradeneeded=()=>{const db=request.result;for(const name of BASE_STORES)if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'});if(!db.objectStoreNames.contains('syncQueue')){const queue=db.createObjectStore('syncQueue',{keyPath:'eventId'});queue.createIndex('status','status');queue.createIndex('entityKey','entityKey');queue.createIndex('userId','userId');}if(!db.objectStoreNames.contains('syncMeta'))db.createObjectStore('syncMeta',{keyPath:'id'});if(!db.objectStoreNames.contains('progressBackups'))db.createObjectStore('progressBackups',{keyPath:'id'});};request.onsuccess=()=>{clearTimeout(blockedTimer);if(settled){request.result.close();return;}settled=true;const db=request.result;db.onversionchange=()=>{db.close();dbPromise=null;};resolve(db);};request.onerror=()=>{clearTimeout(blockedTimer);fail(request.error);};});return dbPromise;}
export async function get(store,id){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function put(store,value,options={}){const db=await openDB();const saved=await new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>resolve(value);r.onerror=()=>reject(r.error);});if(options.sync!==false)await Promise.all([...listeners].map(listener=>Promise.resolve(listener({store,value:saved})).catch(()=>{})));return saved;}
export async function all(store){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function allByIndex(store,index,value){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).index(index).getAll(value);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function remove(store,id,options={}){const db=await openDB();await new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error);});if(options.sync!==false)await Promise.all([...listeners].map(listener=>Promise.resolve(listener({store,value:{id,deleted:true}})).catch(()=>{})));}
export function onStoreWrite(listener){listeners.add(listener);return()=>listeners.delete(listener);}
export const progressId=(book,mode='Frases')=>`${book}:${mode}`;
export function mergeProgress(oldProgress,manifest){if(!oldProgress)return null;const ids=new Set(manifest.tracks.map(t=>t.id));if(ids.has(oldProgress.trackId))return oldProgress;const oldIndex=manifest.tracks.findIndex(t=>naturalCompare(t.id,oldProgress.trackId)>0);return {...oldProgress,trackId:manifest.tracks[Math.max(0,oldIndex)]?.id||'',seconds:0,recovered:true};}
export function naturalCompare(a,b){return String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:'base'});}
