import{all,get,onStoreWrite,put,remove}from'./storage.js';
import{recordFromWrite,readSnapshot,writeSnapshot,saveBackup,saveOwnerSnapshot,ownerSnapshot,progressSummary}from'./local_progress_store.js';
import{mergeSnapshots}from'./progress_merge.js';
import{CloudProgressStore}from'./cloud_progress_store.js';

const DEVICE_ID='device-id',ACTIVE_OWNER='active-owner';
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>new Date().toISOString();

export class SyncService extends EventTarget{
  constructor(auth){super();this.auth=auth;this.cloud=new CloudProgressStore(auth);this.deviceId='';this.activeOwner='guest';this.status='device';this.lastSync='';this.error='';this.pendingChoice=null;this.flushing=false;this.timer=null;this.stopWriteListener=null;this.boundOnline=()=>this.flush();this.boundVisibility=()=>{if(document.visibilityState==='hidden')this.flush();};this.boundAuth=event=>this.handleAuth(event.detail.session,event.detail.reason);}
  async init(){const device=await get('syncMeta',DEVICE_ID);this.deviceId=device?.value||id();if(!device)await put('syncMeta',{id:DEVICE_ID,value:this.deviceId},{sync:false});this.activeOwner=(await get('syncMeta',ACTIVE_OWNER))?.value||'guest';this.lastSync=(await get('syncMeta','last-sync'))?.value||'';this.stopWriteListener=onStoreWrite(change=>this.capture(change));window.addEventListener('online',this.boundOnline);document.addEventListener('visibilitychange',this.boundVisibility);this.auth.addEventListener('change',this.boundAuth);await this.handleAuth(this.auth.session);this.timer=setInterval(()=>this.flush(),30000);this.emit();return this;}
  async capture({store,value}){const record=recordFromWrite(store,value);if(!record)return;await this.enqueue(record,this.auth.session?.user?.id||null);this.emit();if(this.canSync())this.scheduleFlush();}
  async enqueue(record,userId){const queue=await all('syncQueue'),existing=queue.find(item=>item.entityKey===record.entityKey&&['pending','failed'].includes(item.status)&&String(item.userId||'')===String(userId||''));const event={eventId:existing?.eventId||id(),deviceId:this.deviceId,userId:userId||null,entityKey:record.entityKey,eventType:record.value?.deleted?'delete':'snapshot',payload:record,clientUpdatedAt:record.updatedAt||now(),retryCount:existing?.retryCount||0,status:'pending'};await put('syncQueue',event,{sync:false});return event;}
  scheduleFlush(){clearTimeout(this.flushDelay);this.flushDelay=setTimeout(()=>this.flush(),1500);}
  canSync(){return navigator.onLine&&Boolean(this.auth.session?.user)&&this.activeOwner===`user:${this.auth.session.user.id}`&&!this.pendingChoice;}
  async handleAuth(session){if(!session?.user){this.pendingChoice=null;if(this.activeOwner.startsWith('user:')){await this.prepareSignOut();location.reload();return;}this.status=navigator.onLine?'device':'offline';this.emit();return;}const owner=`user:${session.user.id}`;if(this.activeOwner===owner){this.status='syncing';this.emit();await this.pullAndMerge().catch(error=>this.fail(error));this.flush();return;}const local=await readSnapshot(),saved=await ownerSnapshot(owner),remote=await this.cloud.loadAll(session.user.id).catch(()=>[]);this.pendingChoice={userId:session.user.id,owner,local,saved,remote,localSummary:await progressSummary(local),cloudSummary:await progressSummary(remote)};this.status='choice';this.dispatchEvent(new CustomEvent('account-choice',{detail:this.pendingChoice}));this.emit();}
  async resolveAccountProgress(strategy){const context=this.pendingChoice;if(!context)return;if(strategy==='cancel'){this.pendingChoice=null;this.status='device';this.emit();return;}await saveBackup(`antes-de-${strategy}`,await readSnapshot());await saveOwnerSnapshot(this.activeOwner);let records;if(strategy==='cloud')records=context.remote.length?context.remote:context.saved;else if(strategy==='local')records=context.local;else records=mergeSnapshots(context.saved.length?mergeSnapshots(context.local,context.saved):context.local,context.remote);await writeSnapshot(records,{clear:true,sync:false});this.activeOwner=context.owner;await put('syncMeta',{id:ACTIVE_OWNER,value:this.activeOwner},{sync:false});this.pendingChoice=null;if(strategy!=='cloud')for(const record of records)await this.enqueue(record,context.userId);for(const event of await all('syncQueue'))if(!event.userId)await remove('syncQueue',event.eventId,{sync:false});this.status='syncing';this.emit();await this.flush();location.reload();}
  async pullAndMerge(){if(!this.canSync())return;const userId=this.auth.session.user.id,remote=await this.cloud.loadAll(userId),local=await readSnapshot(),merged=mergeSnapshots(local,remote);await writeSnapshot(merged,{clear:true,sync:false});for(const record of merged)await this.enqueue(record,userId);}
  async flush(){if(this.flushing||!this.canSync())return;this.flushing=true;this.status='syncing';this.error='';this.emit();try{const userId=this.auth.session.user.id,queue=(await all('syncQueue')).filter(item=>String(item.userId||'')===String(userId)&&['pending','failed'].includes(item.status)).sort((a,b)=>String(a.clientUpdatedAt).localeCompare(String(b.clientUpdatedAt)));for(const event of queue){event.status='syncing';await put('syncQueue',event,{sync:false});try{await this.cloud.applyEvent(userId,event);event.status='synced';event.syncedAt=now();await put('syncQueue',event,{sync:false});}catch(error){event.status='failed';event.retryCount=Number(event.retryCount||0)+1;event.lastError=String(error.message||error).slice(0,240);await put('syncQueue',event,{sync:false});throw error;}}this.lastSync=now();await put('syncMeta',{id:'last-sync',value:this.lastSync},{sync:false});this.status='synced';}catch(error){this.fail(error);}finally{this.flushing=false;this.emit();}}
  fail(error){this.error=error?.message||'No se pudo sincronizar.';this.status=navigator.onLine?'error':'offline';this.emit();}
  async pendingCount(){const userId=this.auth.session?.user?.id||null;return(await all('syncQueue')).filter(item=>['pending','syncing','failed'].includes(item.status)&&String(item.userId||'')===String(userId||'')).length;}
  async prepareSignOut(){if(this.activeOwner.startsWith('user:'))await saveOwnerSnapshot(this.activeOwner);const guest=await ownerSnapshot('guest');await writeSnapshot(guest,{clear:true,sync:false});this.activeOwner='guest';await put('syncMeta',{id:ACTIVE_OWNER,value:'guest'},{sync:false});}
  emit(){this.pendingCount().then(pending=>this.dispatchEvent(new CustomEvent('change',{detail:{status:this.status,lastSync:this.lastSync,error:this.error,pending,choice:this.pendingChoice}})));}
  destroy(){clearInterval(this.timer);clearTimeout(this.flushDelay);this.stopWriteListener?.();window.removeEventListener('online',this.boundOnline);document.removeEventListener('visibilitychange',this.boundVisibility);this.auth.removeEventListener('change',this.boundAuth);}
}
