import{all,get,put}from'./storage.js';
import{authService}from'./auth_service.js';

export const LESSON_XP_RULES=Object.freeze({normal:20,short:10,test:30,unitFinal:50,review:5});
const LEGACY_KEY='migration:japanese-legacy-v1';
const LANGUAGE_ALIASES={mandarin:'chinese','mandarin chinese':'chinese',zh:'chinese',ja:'japanese',ko:'korean',en:'english',fr:'french',de:'german',it:'italian',ru:'russian'};
const emptySummary=()=>({totalXp:0,byLanguage:{},todayXp:0,lastActivity:null,pendingXp:0,completedLessons:0});
const day=value=>String(value||'').slice(0,10);
export function canonicalLanguageId(value=''){const raw=String(value).trim().toLowerCase();return LANGUAGE_ALIASES[raw]||raw.replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'');}
export function storyXpIdentity({bookCode,lesson}={}){const code=String(bookCode||'').trim(),rawLesson=String(lesson??'').trim(),lessonKey=!rawLesson||rawLesson==='0'?'continuous':rawLesson;if(!code)throw new Error('El libro no tiene un código válido para conceder XP.');return{courseId:`story:${code}`,lessonId:`lesson:${lessonKey}`};}
export function isStoryLessonBoundary(tracks=[],index=0){const current=tracks[index];if(!current)return false;const next=tracks[index+1],currentLesson=String(current.lesson??'0').trim()||'0',nextLesson=String(next?.lesson??'0').trim()||'0';return!next||currentLesson!==nextLesson;}
export function lessonEventKey({languageId,courseId,lessonId}){return`lesson-completed:${canonicalLanguageId(languageId)}:${String(courseId).trim()}:${String(lessonId).trim()}`;}
export function xpForLesson({lessonType='normal',xpReward}={}){const explicit=Number(xpReward);if(Number.isFinite(explicit)&&explicit>=0&&explicit<=100)return Math.round(explicit);return LESSON_XP_RULES[lessonType]??LESSON_XP_RULES.normal;}
export function aggregateXpEvents(events=[]){const summary=emptySummary(),today=day(new Date().toISOString());for(const event of events){const xp=Math.max(0,Number(event.xp||0)),language=canonicalLanguageId(event.languageId||'unknown');summary.totalXp+=xp;summary.byLanguage[language]=(summary.byLanguage[language]||0)+xp;if(String(event.serverEventKey||'').startsWith('lesson-completed:'))summary.completedLessons++;if(day(event.earnedAt)===today)summary.todayXp+=xp;if(!summary.lastActivity||String(event.earnedAt)>summary.lastActivity)summary.lastActivity=event.earnedAt;if(event.status==='pending')summary.pendingXp+=xp;}return summary;}
function mergeSummary(remote,localEvents){if(!remote)return aggregateXpEvents(localEvents);const result={...emptySummary(),...remote,byLanguage:{...(remote?.byLanguage||remote?.by_language||{})}},pending=aggregateXpEvents(localEvents.filter(event=>event.status==='pending'));result.totalXp=Number(result.totalXp||result.total_xp||0)+pending.totalXp;result.todayXp=Number(result.todayXp||result.today_xp||0)+pending.todayXp;result.completedLessons=Number(result.completedLessons||result.completed_lessons||0)+pending.completedLessons;result.pendingXp=pending.totalXp;for(const[language,xp]of Object.entries(pending.byLanguage))result.byLanguage[language]=Number(result.byLanguage[language]||0)+xp;result.lastActivity=[result.lastActivity,result.last_activity,pending.lastActivity].filter(Boolean).sort().at(-1)||null;return result;}
function uuid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;}

export class XPService extends EventTarget{
  constructor(auth=authService){super();this.auth=auth;this.remoteSummary=null;this.loading=false;this.syncing=false;this.error='';this.boundAuth=()=>this.onAccountChanged();this.boundOnline=()=>this.flush();}
  ownerKey(){return this.auth.session?.user?.id?`user:${this.auth.session.user.id}`:'guest';}
  async init(){this.auth.addEventListener('change',this.boundAuth);addEventListener('online',this.boundOnline);await this.migrateLegacyLocal();await this.onAccountChanged();return this;}
  async migrateLegacyLocal(){const progress=await get('metadata','jp-guided-progress-v1').catch(()=>null);if(!progress)return;const ownerKey='guest',earnedAt=progress.lastStudyDate||new Date().toISOString();for(const lessonId of new Set(progress.completedLessons||[])){const serverEventKey=lessonEventKey({languageId:'japanese',courseId:'japanese-from-zero',lessonId}),eventKey=`${ownerKey}|${serverEventKey}`;if(await get('xpEvents',eventKey))continue;await put('xpEvents',{eventKey,serverEventKey,eventId:uuid(),ownerKey,eventType:'migration',languageId:'japanese',courseId:'japanese-from-zero',lessonId,xp:0,metadata:{source:'legacy-completed-lessons'},earnedAt,status:'local',retryCount:0},{sync:false});}const xp=Math.min(1000000,Math.max(0,Math.round(Number(progress.xp||0))));if(!xp)return;const eventKey=`${ownerKey}|${LEGACY_KEY}`;if(await get('xpEvents',eventKey))return;await put('xpEvents',{eventKey,serverEventKey:LEGACY_KEY,eventId:uuid(),ownerKey,eventType:'migration',languageId:'japanese',courseId:'japanese-from-zero',lessonId:'legacy',xp,metadata:{source:'jp-guided-progress-v1'},earnedAt,status:'local',retryCount:0},{sync:false});}
  async claimGuestEvents(){const userId=this.auth.session?.user?.id;if(!userId)return;const target=`user:${userId}`,events=(await all('xpEvents')).filter(event=>event.ownerKey==='guest');for(const event of events){const eventKey=`${target}|${event.serverEventKey}`;if(await get('xpEvents',eventKey))continue;await put('xpEvents',{...event,eventKey,ownerKey:target,userId,status:event.eventType==='migration'?'local':'pending',retryCount:0},{sync:false});}}
  async onAccountChanged(){this.remoteSummary=null;this.error='';if(this.auth.session?.user){await this.refreshRemote();await this.flush();}this.emit();}
  async awardLessonXP(input){const languageId=canonicalLanguageId(input.languageId),courseId=String(input.courseId||'').trim(),lessonId=String(input.lessonId||'').trim();if(!languageId||!courseId||!lessonId)throw new Error('La lección no tiene un identificador válido para conceder XP.');const serverEventKey=lessonEventKey({languageId,courseId,lessonId}),ownerKey=this.ownerKey(),eventKey=`${ownerKey}|${serverEventKey}`,existing=await get('xpEvents',eventKey);if(existing)return{awarded:false,xp:0,event:existing,summary:await this.getSummary()};const xp=xpForLesson(input),event={eventKey,serverEventKey,eventId:uuid(),ownerKey,userId:this.auth.session?.user?.id||null,eventType:'lesson_completed',languageId,courseId,lessonId,xp,metadata:{score:Number(input.score||0),lessonType:input.lessonType||'normal'},earnedAt:input.completedAt||new Date().toISOString(),status:this.auth.session?.user?'pending':'local',retryCount:0};await put('xpEvents',event,{sync:false});this.emit();if(navigator.onLine&&this.auth.session?.user)this.flush();return{awarded:true,xp,event,summary:await this.getSummary()};}
  async localEvents(){const owner=this.ownerKey();return(await all('xpEvents')).filter(event=>event.ownerKey===owner);}
  async getSummary(){const events=await this.localEvents();return this.auth.session?.user?mergeSummary(this.remoteSummary,events):aggregateXpEvents(events);}
  async refreshRemote(){if(!this.auth.client||!this.auth.session?.user||!navigator.onLine)return this.getSummary();this.loading=true;try{await this.auth.client.rpc('migrate_my_legacy_xp');const{data,error}=await this.auth.client.rpc('get_my_xp_summary');if(error)throw error;this.remoteSummary=data||emptySummary();this.error='';}catch(error){this.error=error.message||'No se pudo cargar el XP online.';}finally{this.loading=false;this.emit();}return this.getSummary();}
  async flush(){if(this.syncing||!this.auth.client||!this.auth.session?.user||!navigator.onLine)return;this.syncing=true;this.emit();const owner=this.ownerKey();try{for(const event of(await all('xpEvents')).filter(item=>item.ownerKey===owner&&item.status==='pending')){const{data,error}=await this.auth.client.rpc('complete_lesson',{p_language_id:event.languageId,p_course_id:event.courseId,p_lesson_id:event.lessonId,p_completed_at:event.earnedAt,p_client_event_id:event.eventId});if(error)throw error;event.status='confirmed';event.confirmedAt=new Date().toISOString();await put('xpEvents',event,{sync:false});if(data?.summary)this.remoteSummary=data.summary;}await this.refreshRemote();this.error='';}catch(error){this.error=error.message||'El XP queda guardado y se sincronizará después.';for(const event of(await all('xpEvents')).filter(item=>item.ownerKey===owner&&item.status==='pending')){event.retryCount=Number(event.retryCount||0)+1;await put('xpEvents',event,{sync:false});}}finally{this.syncing=false;this.emit();}}
  emit(){this.dispatchEvent(new CustomEvent('change'));}
  destroy(){this.auth.removeEventListener('change',this.boundAuth);removeEventListener('online',this.boundOnline);}
}

export const xpService=new XPService();
